---
language: python
python:
  - 2.7
#  - 3.3
#  - 3.4
#  - 3.5
cache:
  directories:
    - $HOME/.cache/pip
env:
#  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.4.1.0
#  - ANSIBLE_VERSION=2.3.1.0
#  - ANSIBLE_VERSION=2.2.2.0  
cache: bundler
#sudo: false
sudo: required
dist: travis_lts

branches:
  only:
    - master

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
 - sudo apt-get install -qq curl

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

  # Update Ansible submodule.
  #- git pull && git submodule init
  ##- git submodule update && git submodule status
  #- git submodule foreach git checkout master

  #- ansible-galaxy install -r requirements.yml -p ./roles/ --ignore-errors

script:
  # Check ansible version
  - ansible --version

  # Add ansible.cfg to pick up roles path.
  #- "{ echo '[defaults]'; echo 'roles_path = ./roles'; } >> ansible.cfg"
  #- export ANSIBLE_ROLES_PATH="../"

  # Prepare tests
  #- echo localhost > hosts

  # Check syntax
  # Check the role/playbook's syntax.
  - ansible-playbook --syntax-check -i ./hosts -vvvv ./workstation.yml --connection=local -e "python_versions=[2.7]"

  # First run
  # Run the role/playbook with ansible-playbook.
  #- travis_wait 30 
  - ansible-playbook -i ./hosts ./workstation.yml --connection=local --sudo -vvvv -e "python_versions=[2.7]"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    recipients:
      - alban.andrieu@nabla.mobi
#      - other@example.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
