---
# from galaxy
# ansible-galaxy install -r requirements.yml --ignore-errors
# ansible-galaxy install -r requirements.yml -p ./roles/ --ignore-errors
# ansible-galaxy collection install -r requirements.yml --force
# ansible-galaxy collection list
# ansible-galaxy collection install community.general --force
# ansible-galaxy collection install devsec.hardening

collections:
  - name: community.crypto
    version: '>=2.2.0'
  - name: community.general
    version: '>=4.5.0'
  - name: ansible.utils
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.windows
  - name: devsec.hardening
  - name: community.docker
  - name: containers.podman

roles:
  - src: https://github.com/AlbanAndrieu/ansible-administration.git
    name: albanandrieu.administration
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-cmake.git
    name: albanandrieu.cmake
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-common.git
    name: albanandrieu.ansible_common
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-conky.git
    name: albanandrieu.conky
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-cpp.git
    name: albanandrieu.cpp
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-dns.git
    name: albanandrieu.ansible_dns
    version: master
  - src: https://github.com/AlbanAndrieu/ansible-dropbox.git
    name: albanandrieu.dropbox
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-gcc.git
    name: albanandrieu.gcc
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-hostname.git
    name: albanandrieu.ansible_hostname
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-jdiskreport.git
    name: albanandrieu.jdiskreport
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-scons.git
    name: albanandrieu.scons
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-selenium.git
    name: albanandrieu.selenium
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-shell.git
    name: albanandrieu.shell
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-tomcat.git
    name: albanandrieu.tomcat
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-xvbf.git
    name: albanandrieu.xvbf
    version: master

  - src: https://github.com/AlbanAndrieu/devbox.chrome.git
    name: chrome
    version: master

  - src: https://github.com/geerlingguy/ansible-role-ntp.git
    name: geerlingguy.ntp
    version: master

  - src: https://github.com/geerlingguy/ansible-role-repo-epel.git
    name: geerlingguy.repo-epel
    version: master
  - src: https://github.com/geerlingguy/ansible-role-repo-remi.git
    name: geerlingguy.repo-remi
    version: master

  - src: https://github.com/geerlingguy/ansible-role-docker.git
    name: geerlingguy.docker
    version: master

  - src: https://github.com/gantsign/ansible-role-maven.git
    name: maven
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-nodejs.git
    name: geerlingguy.nodejs
    version: master
  - src: https://github.com/Stouts/Stouts.python.git
    name: python
    version: master

  - src: https://github.com/geerlingguy/ansible-role-security.git
    name: geerlingguy.security
    version: master

  - src: https://github.com/geerlingguy/ansible-role-sonar-runner.git
    name: geerlingguy.sonar-runner
    version: master

  - src: https://github.com/AlbanAndrieu/ansible-galaxy.ubuntu.virtualbox.git
    name: albanandrieu.virtualbox
    version: master
