---
- hosts: localhost
  gather_facts: yes

  tasks:
    - name: run_command
      action: run_cmd cmd=date
      register: user

    - debug: msg="{{ user.msg }}"

    - debug: msg="Hostname is {{ ansible_hostname }}"

- hosts: localhost
  become: true
  gather_facts: false

  roles:
    - { role: ./, dash_enabled: false, webapps_enabled: false, apache_create_vhosts: false }
