---

- name: cloud | Install multipass
  snap:
    name: multipass
    classic: true
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(19.04, '>=')
  tags: package

- name: cloud | Install kubectl
  snap:
    name: kubectl
    classic: true
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(19.04, '>=')
  tags: package
