---
- name: workstation | Install c++ requirement
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['19.04', '19.10'])
  tags: cpp
  with_items:
    - valkyrie

- name: workstation | Install c++ requirement
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  tags: cpp
  with_items:
    - valgrind
    - google-perftools
    - clang
    - flawfinder
    - cppcheck
    - ggcov
    - gperf
    - doxygen

- name: workstation | Install c++ requirement
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['12.04', '14.04'])
  tags: cpp
  with_items:
    - rpmlint
    - complexity # for c
