---
- name: workstation | Install debuging tools
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - ack
    - command-not-found
    - dstat
    - htop
    - iftop
    - etherape
    - iptraf-ng
    - nload
    - avahi-utils
    - mtr
    - iotop
    - iperf
    - fping
    - lsof
    - socat # socat unix-connect:/tmp/haproxy.socket stdio
    - ltrace
    - multitail
    - ncdu
    - pciutils
    - pstack
    - pv
    - smem
    - socat
    - strace
    - sysstat
    - tmux
    - tree
    - tshark
    - cpu-x
    - lm-sensors
    - jq # for json https://stedolan.github.io/jq/download/
  tags:
    - package
    - monitoring

- name: workstation | Install system debuging tools
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - systemtap
    #- linux-headers-generic
  tags:
    - package
    - system

- name: workstation | Add linux header for debuging system
  shell: apt-get install linux-headers-$(uname -r)
  #  changed_when: false
  become: true
  #  ignore_errors: true
  tags:
    - package
    - headers
    - system

- name: workstation | Add debuging symbol
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - ubuntu-dbgsym-keyring
    #- xserver-xorg-core-dbgsym
  #  ignore_errors: true
  tags:
    - package
    - headers
    - system

#sudo apt-get install gnome-shell-dbgsym libglib2.0-*dbgsym libgtk*-dbgsym

- name: workstation | Add putty
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - putty # for netgear
  tags:
    - package
    - serial
    - ssh
    - netgear

- name: workstation | Add wakeonlan
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - wakeonlan  # for freenas
  tags:
    - package
    - freenas
