
- name: workstation | Install useless tool
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['14.04', '16.04'])
  tags: screenfetch
  with_items:
   - screenfetch
  become: true
  ignore_errors: true

# See https://github.com/nvbn/thefuck

- name: workstation | Install thefuck tool
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['12.04', '14.04'])
  with_items:
   - python3-dev
   - python3-pip
   - python3-setuptools
  become: true
  ignore_errors: true

- name: workstation  | Install thefuck
  pip:
    name: "{{ item }}"
    executable: "pip3"
  with_items:
    - thefuck
  when: ansible_python_version | version_compare('2.7', '>=')
  become: true
  ignore_errors: true

# See https://github.com/acaudwell/Gource

- name: workstation | Install gource tool for git
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['12.04', '14.04'])
  with_items:
   - gource
  become: true
  ignore_errors: true
