
- name: workstation | Install useless tool
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (ansible_distribution_version not in ['14.04','16.04'])
  tags: android
  with_items:
   - screenfetch
  become: yes   
  ignore_errors: true
