---
# TODO below is making failing teams-for-linux
# - name: music | Create a link to music
#   file:
#     src="/media/music"
#     dest="{{ home }}/Music"
#     state=link
#     owner="{{ user }}"
#     # group="{{ eclipse_group }}"
#   become: true
#   tags: eclipse_setup

- name: workstation | Install minidlna tools
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(19.04, '>=')
  with_items:
    - minidlna
