---
#TODO https://doc.ubuntu-fr.org/optimisation

- name: workstation | Install kernel cleaning utilities tools
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  tags: package
  with_items:
    - byobu
  become: true

- name: workstation | Cron | Purge kernel images @reboot special time
  cron:
    name: Purge kernel images
    special_time: reboot
    job: apt-get -y autoremove ; purge-old-kernels -y --keep 3 -q
    cron_file: purge_kernel_images
    user: root
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  become: true

- name: workstation | Install tuning utilities tools
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  tags: package
  with_items:
    - tuned
  become: true

# sudo systemctl status tuned
# tuned-adm list
# sudo tuned-adm profile desktop-powersave
# sudo tuned-adm verify
