---
# See https://www.linuxuprising.com/2020/01/4-tools-to-record-your-linux-desktop.html

# See https://doc.ubuntu-fr.org/recordmydesktop
- name: workstation | Install record video tools
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(19.10, '<=')
  tags: package
  with_items:
    - recordmydesktop
    #- qt-recordmydesktop
    - gtk-recordmydesktop # Ubuntu 20 missing

# Switching to https://www.linuxuprising.com/2020/05/simplescreenrecorder-updated-with.html
- name: workstation | Install record video tools
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(19.10, '<=')
  tags: package
  with_items:
    - simplescreenrecorder
