---
# ruby-bundler for bundle init
- name: brew | Install dependencies for ruby requirement
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }} update_cache=yes"
  with_items:
    - ruby-bundler
    - ruby-dev
  become: true
