---

- name: skype | Install skype fixes
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }}"
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and skype_enabled
  tags: skype_setup
  with_items:
    - gtk2-engines-murrine:i386
    - gtk2-engines-pixbuf:i386
    - sni-qt:i386
    - libjpeg62:i386

#See https://www.onmsft.com/office365/how-to-get-microsoft-teams-app-on-linux-and-ubuntu
#sudo snap install teams-for-linux
- name: workstation | Install teams
  snap:
    name: teams-for-linux
    classic: true
  become: true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and ansible_distribution_version is version_compare(19.04, '>=')
  tags:
   - package
   - teams
