---
dependency:
  name: galaxy
  enabled: false
  options:
    ignore-errors: true
driver:
  name: docker
# lint: |
#   set -e
#   yamllint .
#   ansible-lint
platforms:
  - name: instance
    image: ubuntu:22.04
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
